name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |-
            Release of version ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Get Server JAR Path
        id: get_server_jar_path
        run: echo "path=$(ls server/build/libs/*.jar)" >> $GITHUB_OUTPUT

      - name: Upload Server JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get_server_jar_path.outputs.path }}
          asset_name: chunked-upload-server.jar
          asset_content_type: application/java-archive

      - name: Get Client JAR Path
        id: get_client_jar_path
        run: echo "path=$(ls client/build/libs/*.jar)" >> $GITHUB_OUTPUT

      - name: Upload Client JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get_client_jar_path.outputs.path }}
          asset_name: chunked-upload-client.jar
          asset_content_type: application/java-archive
