name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build client JAR
        run: ./gradlew :client:build

      - name: Prepare client release zip
        run: |
          mkdir -p client-release/libs
          mkdir -p client-release/build
          cp client/dependencies/download-dependencies.bat client-release/libs/
          cp client/dependencies/download-dependencies.sh client-release/libs/
          cp model/build/libs/model.jar client-release/libs/
          cp client/run-client.bat client-release/
          cp client/run-client.sh client-release/
          cp client/build/libs/client.jar client-release/build/
          cd client-release
          zip -r ../client.zip .
        shell: bash

      - name: Prepare server release zip
        run: |
          mkdir -p server-release/libs
          mkdir -p server-release/build
          cp server/dependencies/download-dependencies.bat server-release/libs/
          cp server/dependencies/download-dependencies.sh server-release/libs/
          cp model/build/libs/model.jar server-release/libs/
          cp server/run-server.bat server-release/
          cp server/run-server.sh server-release/
          cp server/build/libs/server.jar server-release/build/
          cp server/create-user.bat server-release/
          cp server/create-user.sh server-release/
          cd server-release
          zip -r ../server.zip .
        shell: bash

      - name: Delete existing release for tag
        run: |
          gh release delete ${{ github.ref_name }} --cleanup-tag --yes || echo "No existing release to delete"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref }}
          body: |-
            Release of version ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload server.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: server.zip
          asset_name: server.zip
          asset_content_type: application/zip

      - name: Upload client.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: client.zip
          asset_name: client.zip
          asset_content_type: application/zip

      - name: Upload model.jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: model/build/libs/model.jar
          asset_name: model.jar
          asset_content_type: application/java-archive

      - name: Get Server JAR Path
        id: get_server_jar_path
        run: |
          echo "path=$(ls server/build/libs/*.jar | head -n 1)" >> $GITHUB_OUTPUT
          echo "Server JAR path: $(ls server/build/libs/*.jar | head -n 1)"
          echo "path=$(ls server/build/libs/*.jar | head -n 1)" > $GITHUB_OUTPUT

      - name: Upload Server JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get_server_jar_path.outputs.path }}
          asset_name: server.jar
          asset_content_type: application/java-archive

      - name: Get Client JAR Path
        id: get_client_jar_path
        run: |
          echo "path=$(ls client/build/libs/*.jar | head -n 1)" >> $GITHUB_OUTPUT
          echo "Client JAR path: $(ls client/build/libs/*.jar | head -n 1)"
          echo "path=$(ls client/build/libs/*.jar | head -n 1)" > $GITHUB_OUTPUT

      - name: Upload Client JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get_client_jar_path.outputs.path }}
          asset_name: client.jar
          asset_content_type: application/java-archive
